language: rust
rust: 
  - nightly
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -q update
  - sudo apt-get install -qq -y libsodium-dev
